import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

/**
 * Pages under `src/content/docs/` are generated by `scripts/sync-docs.mjs` from
 * the repository's Markdown, and are gitignored. Run `pnpm sync` (or any of the
 * dev/build scripts, which do it for you) before expecting content here.
 */
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
